---
- hosts: icarus2.deudtens.com
  vars:
    http_port: 80
  remote_user: oservieres
  sudo: yes
  tasks:
  - include_vars: vars.yml
  - name: install nginx
    apt: pkg=nginx state=latest
  - name: ensure nginx is running
    service: name=nginx state=started
  - name: install mysql
    apt: pkg={{ item }} state=latest
    with_items:
    - mysql-client
    - mysql-server
    - python-mysqldb
  - name: install php5
    apt: pkg=php5 state=latest
  - mysql_user: name=root password={{ mysql_root_password }}
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
